#include "ATMEGA32_REG.h"
#include "BIT_MATH.h"
#include "STD_TYPES.h"
#include "DCM_interface.h"
#include "DCM_config.h"

void DCM_stopAllmotors(void)
{
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_1_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_2_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_3_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_4_PIN);
}
void DCM_moveForward(void)
{
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_1_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_2_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_3_PIN);
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_4_PIN);
}
void DCM_moveBackwards(void)
{
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_1_PIN);
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_2_PIN);
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_3_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_4_PIN);
}
void DCM_moveLeft(void)
{
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_1_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_2_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_3_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_4_PIN);
}
void DCM_moveRight(void)
{
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_1_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_2_PIN);
	CLR_BIT(DCM_MOTOR_PORT, DCM_INT_3_PIN);
	SET_BIT(DCM_MOTOR_PORT, DCM_INT_4_PIN);	
}